#!/usr/bin/env php
<?php
/**
 * This file is part of the PHPLucidFrame library.
 * Shell script for invoking PHPLucidFrame shell commands using `php lucidframe`
 *
 * @package     LucidFrame\Console
 * @since       PHPLucidFrame v 1.11.0
 * @copyright   Copyright (c), PHPLucidFrame.
 * @author      Sithu K. <cithukyaw@gmail.com>
 * @link        http://phplucidframe.sithukyaw.com
 * @license     http://www.opensource.org/licenses/mit-license.php MIT License
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.txt
 */

require_once 'bootstrap.php';

new LucidFrame\Console\Console();
