<?php
/**
 * This file is part of the PHPLucidFrame library.
 *
 * @package     PHPLucidFrame\Test
 * @since       PHPLucidFrame v 1.13.0
 * @copyright   Copyright (c), PHPLucidFrame.
 * @link        http://phplucidframe.com
 * @license     http://www.opensource.org/licenses/mit-license.php MIT License
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE
 */

namespace LucidFrame\Test;

/**
 * Collects test files matching a PCRE pattern and descends into sub-folders,
 * adding each sub-folder as a nested test suite (a "group", e.g. core, classes,
 * console, db, helpers). File matching is done against the basename and the
 * normalized (forward-slashed) path so it behaves identically on Windows and *nix.
 */
class RecursivePatternCollector extends \SimpleCollector
{
    /** @var string */
    private $pattern;

    /**
     * Constructor
     *
     * @param string $pattern PCRE pattern matched against the file basename or the normalized path
     */
    public function __construct($pattern = '~\.test\.php$~')
    {
        $this->pattern = $pattern;
    }

    /**
     * Adds files matching the pattern; sub-folders become nested test suites.
     *
     * @param object $test     the suite to add to
     * @param string $filename a file or directory path as generated by collect()
     *
     * @return void
     */
    protected function handle(&$test, $filename)
    {
        if (is_dir($filename)) {
            $group = new \TestSuite(basename($filename));
            $this->collect($group, $filename);
            if ($group->getSize() > 0) {
                $test->add($group);
            }
            return;
        }

        $path = str_replace('\\', '/', $filename);

        if (preg_match($this->pattern, basename($path)) || preg_match($this->pattern, $path)) {
            $test->addFile($filename);
        }
    }
}

class LucidFrameTestSuite extends \TestSuite
{
    protected $files;
    protected $target = array();

    public function __construct($target = null)
    {
        parent::__construct();

        switch ($target) {
            case 'lib':
                $this->target[] = dirname(__FILE__) . '/lib/';
                break;

            case 'app':
                $this->target[] = dirname(__FILE__) . '/app/';
                break;

            default:
                $this->target[] = dirname(__FILE__) . '/lib/';
                $this->target[] = dirname(__FILE__) . '/app/';
                break;
        }
    }

    public function execute()
    {
        $files = array();
        $options = array();

        if (PHP_SAPI == 'cli') {
            $options = getopt('f:', array('file:'));
        } else {
            if (isset($_GET['f'])) {
                $options['f'] = $_GET['f'];
            }
            if (isset($_GET['file'])) {
                $options['file'] = $_GET['file'];
            }
        }

        if (isset($options['f'])) {
            $files += explode(',', $options['f']);
        }

        if (isset($options['file'])) {
            $files += explode(',', $options['file']);
        }

        $this->files = array_map('trim', $files);

        if (count($this->files)) {
            foreach ($this->files as $fileName) {
                $this->collectFiles(new RecursivePatternCollector($this->buildPattern($fileName)));
            }
        } else {
            $this->collectFiles(new RecursivePatternCollector('~\.test\.php$~'));
        }
    }

    /**
     * Collects test files from all target directories using the given collector
     *
     * @param RecursivePatternCollector $collector
     *
     * @return void
     */
    private function collectFiles(RecursivePatternCollector $collector)
    {
        foreach ($this->target as $dir) {
            $this->collect($dir, $collector);
        }
    }

    /**
     * Builds an anchored PCRE pattern for the -f/--file filter. Accepts a plain
     * test name ("utility_helper") or a group-qualified path ("helpers/utility_helper",
     * "db/driver_factory"). Both "/" and "\" group separators are supported.
     *
     * @param string $fileName
     *
     * @return string
     */
    private function buildPattern($fileName)
    {
        $escaped = str_replace('/', '[/\\\\]', preg_quote($fileName, '~'));

        return '~(^|[/\\\\])' . $escaped . '\.test\.php$~';
    }
}
