<?php
/**
 * This file is part of the PHPLucidFrame library.
 *
 * @package     PHPLucidFrame\Test
 * @since       PHPLucidFrame v 4.0.0
 * @copyright   Copyright (c), PHPLucidFrame.
 * @link        http://phplucidframe.com
 * @license     http://www.opensource.org/licenses/mit-license.php MIT License
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE
 */

namespace LucidFrame\Test;

/**
 * Collects test files matching a PCRE pattern and descends into sub-folders,
 * adding each sub-folder as a nested test suite (a "group", e.g. core, classes,
 * console, db, helpers). File matching is done against the basename and the
 * normalized (forward-slashed) path so it behaves identically on Windows and *nix.
 */
class RecursivePatternCollector extends \SimpleCollector
{
    /** @var string */
    private $pattern;

    /**
     * Constructor
     *
     * @param string $pattern PCRE pattern matched against the file basename or the normalized path
     */
    public function __construct($pattern = '~\.test\.php$~')
    {
        $this->pattern = $pattern;
    }

    /**
     * Adds files matching the pattern; sub-folders become nested test suites.
     *
     * @param object $test     the suite to add to
     * @param string $filename a file or directory path as generated by collect()
     *
     * @return void
     */
    protected function handle(&$test, $filename)
    {
        if (is_dir($filename)) {
            $group = new \TestSuite(basename($filename));
            $this->collect($group, $filename);
            if ($group->getSize() > 0) {
                $test->add($group);
            }
            return;
        }

        $path = str_replace('\\', '/', $filename);

        if (preg_match($this->pattern, basename($path)) || preg_match($this->pattern, $path)) {
            $test->addFile($filename);
        }
    }
}
