<?php

use LucidFrame\Core\Form;
use LucidFrame\Core\Validation;
use LucidFrame\Test\LucidFrameTestCase;

/**
 * Unit Test for form_helper.php
 * Covers form_set, form_token, form_validate, form_value, form_htmlValue,
 * form_selected and form_checked.
 */
class FormHelperTestCase extends LucidFrameTestCase
{
    /** @var array Saved $_POST, restored after each test */
    private $savedPost;
    /** @var string|null Saved HTTP_REFERER, restored after each test */
    private $savedReferer;
    /** @var string Saved siteDomain config, restored after each test */
    private $savedSiteDomain;

    public function setUp()
    {
        parent::setUp();

        $this->savedPost = $_POST;
        $this->savedReferer = isset($_SERVER['HTTP_REFERER']) ? $_SERVER['HTTP_REFERER'] : null;
        $this->savedSiteDomain = _cfg('siteDomain');
        $_POST = array();
        Form::$formToken = '';
        Form::init();
    }

    public function tearDown()
    {
        $_POST = $this->savedPost;
        if ($this->savedReferer === null) {
            unset($_SERVER['HTTP_REFERER']);
        } else {
            $_SERVER['HTTP_REFERER'] = $this->savedReferer;
        }
        _cfg('siteDomain', $this->savedSiteDomain);
        Form::init();

        parent::tearDown();
    }

    /**
     * Simulate a valid form submission: generate the CSRF token, post its
     * encrypted value and set the referer to the current site domain.
     *
     * The site domain config carries the scheme in the test parameter file
     * (e.g. "http://localhost"). Form::validate compares the config value to
     * the parsed referer HOST (which has no scheme), so use the bare host here.
     */
    private function prepareValidFormToken()
    {
        $host = preg_replace('#^https?://#i', '', _cfg('siteDomain'));
        _cfg('siteDomain', $host);

        Form::generateToken();
        $_POST[Form::getCsrfTokenName()] = _encrypt(Form::$formToken);
        $_SERVER['HTTP_REFERER'] = 'http://' . $host . '/form';
    }

    public function testForFormSet()
    {
        form_set('success', true);
        $this->assertTrue(Form::get('success'));

        form_set('redirect', '/post/list');
        $this->assertEqual(Form::get('redirect'), '/post/list');

        form_set('error', array('name' => 'The name is required.'));
        $this->assertEqual(Form::get('error'), array('name' => 'The name is required.'));
    }

    public function testForFormTokenGeneration()
    {
        $this->assertEqual(Form::$formToken, '');

        // form_token() echoes the hidden input for the CURRENT token;
        // the token itself is generated by Form::generateToken()
        Form::generateToken();
        ob_start();
        form_token();
        $html = ob_get_clean();

        $this->assertNotEqual(Form::$formToken, '');
        $this->assertIsString(Form::$formToken);
        $this->assertPattern('/^[0-9a-f]{32}$/', Form::$formToken);
        $this->assertStringContainsString('lc_formToken_' . _cfg('formTokenName'), $html);
    }

    public function testForFormTokenRegeneration()
    {
        Form::generateToken();
        $first = Form::$formToken;

        Form::generateToken();
        $second = Form::$formToken;

        $this->assertNotEqual($first, $second);
    }

    public function testForFormCsrfTokenName()
    {
        $this->assertEqual(Form::getCsrfTokenName(), 'lc_formToken_' . _cfg('formTokenName'));
    }

    public function testForFormValidateSuccess()
    {
        $this->prepareValidFormToken();

        $validations = array(
            'name'  => array(
                'caption' => 'Name',
                'value'   => 'John Doe',
                'rules'   => array('mandatory', 'alphaNumericSpace'),
            ),
            'email' => array(
                'caption' => 'Email',
                'value'   => 'john@example.com',
                'rules'   => array('mandatory', 'email'),
            ),
        );

        $this->assertTrue(form_validate($validations));
        $this->assertCount(0, Validation::get('errors'));
    }

    public function testForFormValidateLooksUpData()
    {
        $this->prepareValidFormToken();

        $validations = array(
            'name'  => array(
                'caption' => 'Name',
                'rules'   => array('mandatory'),
            ),
            'email' => array(
                'caption' => 'Email',
                'rules'   => array('mandatory', 'email'),
            ),
        );
        $data = array(
            'name'  => 'John Doe',
            'email' => 'john@example.com',
        );

        $this->assertTrue(form_validate($validations, $data));
    }

    public function testForFormValidateFailure()
    {
        $this->prepareValidFormToken();

        $validations = array(
            'name'  => array(
                'caption' => 'Name',
                'value'   => '',
                'rules'   => array('mandatory'),
            ),
            'email' => array(
                'caption' => 'Email',
                'value'   => 'not-an-email',
                'rules'   => array('email'),
            ),
        );

        $this->assertFalse(form_validate($validations));

        $errors = Validation::get('errors');
        $this->assertCount(2, $errors);
        $this->assertEqual($errors[0]['field'], 'name');
        $this->assertPattern("/'Name' is required\./", $errors[0]['message']);
        $this->assertEqual($errors[1]['field'], 'email');
    }

    public function testForFormValidateWithCustomMessage()
    {
        $this->prepareValidFormToken();

        $validations = array(
            'name' => array(
                'caption'  => 'Name',
                'value'    => '',
                'rules'    => array('mandatory'),
                'messages' => array('mandatory' => 'Please fill in your name.'),
            ),
        );

        $this->assertFalse(form_validate($validations));

        $errors = Validation::get('errors');
        $this->assertCount(1, $errors);
        $this->assertEqual($errors[0]['message'], 'Please fill in your name.');
    }

    public function testForFormValueWithDefaultOnly()
    {
        // No POST data available
        $this->assertEqual(form_value('name', 'John Doe'), _h('John Doe'));
        $this->assertEqual(form_value('name'), '');
    }

    public function testForFormValueWithPostedData()
    {
        $_POST = array('name' => 'Jane Doe');

        $this->assertEqual(form_value('name', 'John Doe'), _h('Jane Doe'));
        // The posted value is HTML-escaped
        $_POST = array('name' => '<b>Jane</b>');
        $this->assertEqual(form_value('name'), _h('<b>Jane</b>'));
    }

    public function testForFormHtmlValue()
    {
        // No POST data: the default value is returned escaped
        $this->assertEqual(form_htmlValue('body', '<p>Body</p>'), _h('<p>Body</p>'));

        // With POST data: the posted value is XSS-filtered and escaped
        $_POST = array('body' => '<p>Body</p>');
        $this->assertEqual(form_htmlValue('body'), _h(_xss('<p>Body</p>')));

        // A field missing in POST returns an empty string
        $this->assertEqual(form_htmlValue('missing'), '');
    }

    public function testForFormSelectedWithDefaultOnly()
    {
        $this->assertEqual(form_selected('status', 1, 1), 'selected="selected"');
        $this->assertEqual(form_selected('status', 2, 1), '');
    }

    public function testForFormSelectedWithPostedData()
    {
        $_POST = array('status' => 2);

        $this->assertEqual(form_selected('status', 2, 1), 'selected="selected"');
        $this->assertEqual(form_selected('status', 1, 1), '');
    }

    public function testForFormSelectedWithPostedArray()
    {
        $_POST = array('group' => array('a', 'b'));

        $this->assertEqual(form_selected('group[]', 'a'), 'selected="selected"');
        $this->assertEqual(form_selected('group[]', 'c'), '');
    }

    public function testForFormCheckedWithDefaultOnly()
    {
        $this->assertEqual(form_checked('active', 'yes', 'yes'), 'checked="checked"');
        $this->assertEqual(form_checked('active', 'yes', 'no'), '');
    }

    public function testForFormCheckedWithPostedData()
    {
        $_POST = array('active' => 'no');

        $this->assertEqual(form_checked('active', 'no', 'yes'), 'checked="checked"');
        $this->assertEqual(form_checked('active', 'yes', 'yes'), '');
    }
}
